### ISSUE TITLE
COVID-Net Plugin: Design & HTML/CSS for plugin PDF output

### ISSUE THREAD

**Issue by mairin** [FNNDSC/cube-design#17]
Current mockup:
https://xd.adobe.com/view/91457d02-00bc-4580-a25f-46e016c3e318-c416/

The code for this will eventually end up here:
https://github.com/darwinai/pl-pdfgeneration/tree/master/pdfgeneration/pdftemplate

(@dcaryll)

**Comment by mairin** [comment]
@dcaryll is this work complete? Should we close ticket if so?

**Comment by junaruga** [comment]
@dcaryll ping.

**Comment by mairin** [comment]
This work is complete as per a demo of the functionality so I am going to close this fixed. Thanks @dcaryll !
